//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveJimaCore.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Russian {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Russian() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EveJimaCore.Localization.Russian", typeof(Russian).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка данных с сайта CCP SSO (single sign-on)..
        /// </summary>
        internal static string LoadAllPilotesFromStorage {
            get {
                return ResourceManager.GetString("LoadAllPilotesFromStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Loadpilotesfromcache {
            get {
                return ResourceManager.GetString("Loadpilotesfromcache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить пилотов из кэша. Пилотов  {0}.
        /// </summary>
        internal static string LoadPilotsFromCache {
            get {
                return ResourceManager.GetString("LoadPilotsFromCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало авторизации для пилота {0}.
        /// </summary>
        internal static string StartAuthorizePilot {
            get {
                return ResourceManager.GetString("StartAuthorizePilot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закладки.
        /// </summary>
        internal static string Tab_Bookmarks {
            get {
                return ResourceManager.GetString("Tab_Bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анализировать.
        /// </summary>
        internal static string Tab_Bookmarks_Analyze {
            get {
                return ResourceManager.GetString("Tab_Bookmarks_Analyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закладки.
        /// </summary>
        internal static string Tab_Bookmarks_Bookmarks {
            get {
                return ResourceManager.GetString("Tab_Bookmarks_Bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить.
        /// </summary>
        internal static string Tab_Bookmarks_Clear {
            get {
                return ResourceManager.GetString("Tab_Bookmarks_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить космические сигнатуры.
        /// </summary>
        internal static string Tab_Bookmarks_PasteCosmicSignatures {
            get {
                return ResourceManager.GetString("Tab_Bookmarks_PasteCosmicSignatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить закладки координат.
        /// </summary>
        internal static string Tab_Bookmarks_PasteLocationBookmarks {
            get {
                return ResourceManager.GetString("Tab_Bookmarks_PasteLocationBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигнатуры.
        /// </summary>
        internal static string Tab_Bookmarks_Signatures {
            get {
                return ResourceManager.GetString("Tab_Bookmarks_Signatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Браузер.
        /// </summary>
        internal static string Tab_Browser {
            get {
                return ResourceManager.GetString("Tab_Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        internal static string Tab_Information {
            get {
                return ResourceManager.GetString("Tab_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Класс.
        /// </summary>
        internal static string Tab_Information_Class {
            get {
                return ResourceManager.GetString("Tab_Information_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Созвездие.
        /// </summary>
        internal static string Tab_Information_Constellation {
            get {
                return ResourceManager.GetString("Tab_Information_Constellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эффект.
        /// </summary>
        internal static string Tab_Information_Effect {
            get {
                return ResourceManager.GetString("Tab_Information_Effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellatha показывает информацию только для W-Space систем.
        /// </summary>
        internal static string Tab_Information_EllathaWarning {
            get {
                return ResourceManager.GetString("Tab_Information_EllathaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная пропускная масса.
        /// </summary>
        internal static string Tab_Information_MaxJumpMass {
            get {
                return ResourceManager.GetString("Tab_Information_MaxJumpMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная масса.
        /// </summary>
        internal static string Tab_Information_MaxStableMass {
            get {
                return ResourceManager.GetString("Tab_Information_MaxStableMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регион.
        /// </summary>
        internal static string Tab_Information_Region {
            get {
                return ResourceManager.GetString("Tab_Information_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Солнечная система.
        /// </summary>
        internal static string Tab_Information_SolarSystem {
            get {
                return ResourceManager.GetString("Tab_Information_SolarSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статик.
        /// </summary>
        internal static string Tab_Information_Static {
            get {
                return ResourceManager.GetString("Tab_Information_Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Местоположение.
        /// </summary>
        internal static string Tab_Location {
            get {
                return ResourceManager.GetString("Tab_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Центрировать по местоположению.
        /// </summary>
        internal static string Tab_Map_CentreLocationSystem {
            get {
                return ResourceManager.GetString("Tab_Map_CentreLocationSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Центрировать по выбранной системе.
        /// </summary>
        internal static string Tab_Map_CentreSelectedSystem {
            get {
                return ResourceManager.GetString("Tab_Map_CentreSelectedSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команды.
        /// </summary>
        internal static string Tab_Map_Commands {
            get {
                return ResourceManager.GetString("Tab_Map_Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигнатура.
        /// </summary>
        internal static string Tab_Map_CosmicSignature {
            get {
                return ResourceManager.GetString("Tab_Map_CosmicSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Похоронка. Я умер..
        /// </summary>
        internal static string Tab_Map_DeathNotice {
            get {
                return ResourceManager.GetString("Tab_Map_DeathNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить все.
        /// </summary>
        internal static string Tab_Map_DeleteAll {
            get {
                return ResourceManager.GetString("Tab_Map_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        internal static string Tab_Map_Information {
            get {
                return ResourceManager.GetString("Tab_Map_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внешние ссылки.
        /// </summary>
        internal static string Tab_Map_InternalResourses {
            get {
                return ResourceManager.GetString("Tab_Map_InternalResourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Может ли участник удалять системы.
        /// </summary>
        internal static string Tab_Map_IsMemberCanDeleteSystem {
            get {
                return ResourceManager.GetString("Tab_Map_IsMemberCanDeleteSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ карты.
        /// </summary>
        internal static string Tab_Map_Map_Key {
            get {
                return ResourceManager.GetString("Tab_Map_Map_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Владелец карты.
        /// </summary>
        internal static string Tab_Map_MapOwner {
            get {
                return ResourceManager.GetString("Tab_Map_MapOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста введите ключ карты.
        /// </summary>
        internal static string Tab_Map_MessageFillMapKey {
            get {
                return ResourceManager.GetString("Tab_Map_MessageFillMapKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить сигнатуры.
        /// </summary>
        internal static string Tab_Map_PasteSignatures {
            get {
                return ResourceManager.GetString("Tab_Map_PasteSignatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пилоты.
        /// </summary>
        internal static string Tab_Map_Pilot {
            get {
                return ResourceManager.GetString("Tab_Map_Pilot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перезагрузить.
        /// </summary>
        internal static string Tab_Map_Reload {
            get {
                return ResourceManager.GetString("Tab_Map_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранять LowSec системы.
        /// </summary>
        internal static string Tab_Map_SaveLowSec {
            get {
                return ResourceManager.GetString("Tab_Map_SaveLowSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес сервера.
        /// </summary>
        internal static string Tab_Map_ServerAddress {
            get {
                return ResourceManager.GetString("Tab_Map_ServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установки.
        /// </summary>
        internal static string Tab_Map_Settings {
            get {
                return ResourceManager.GetString("Tab_Map_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установки карты.
        /// </summary>
        internal static string Tab_Map_SettingsLabel {
            get {
                return ResourceManager.GetString("Tab_Map_SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигнатуры.
        /// </summary>
        internal static string Tab_Map_Signatures {
            get {
                return ResourceManager.GetString("Tab_Map_Signatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Солнечная система.
        /// </summary>
        internal static string Tab_Map_SolarSystemInformation {
            get {
                return ResourceManager.GetString("Tab_Map_SolarSystemInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить все.
        /// </summary>
        internal static string Tab_Map_UpdateAll {
            get {
                return ResourceManager.GetString("Tab_Map_UpdateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следопыт.
        /// </summary>
        internal static string Tab_Pathfinder {
            get {
                return ResourceManager.GetString("Tab_Pathfinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пилоты.
        /// </summary>
        internal static string Tab_Pilots {
            get {
                return ResourceManager.GetString("Tab_Pilots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установки.
        /// </summary>
        internal static string Tab_Settings {
            get {
                return ResourceManager.GetString("Tab_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор:.
        /// </summary>
        internal static string Tab_Settings_Author {
            get {
                return ResourceManager.GetString("Tab_Settings_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eve Jima версия:.
        /// </summary>
        internal static string Tab_Settings_EveJimaVersion {
            get {
                return ResourceManager.GetString("Tab_Settings_EveJimaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (перезагрузка).
        /// </summary>
        internal static string Tab_Settings_NeedRestart {
            get {
                return ResourceManager.GetString("Tab_Settings_NeedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить установки.
        /// </summary>
        internal static string Tab_Settings_SaveSettings {
            get {
                return ResourceManager.GetString("Tab_Settings_SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать сигнатуры в память:.
        /// </summary>
        internal static string Tab_Settings_ShortSignatureRebuild {
            get {
                return ResourceManager.GetString("Tab_Settings_ShortSignatureRebuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Браузер включен:.
        /// </summary>
        internal static string Tab_Settings_UseBrowser {
            get {
                return ResourceManager.GetString("Tab_Settings_UseBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта червоточен включена:.
        /// </summary>
        internal static string Tab_Settings_UseWormholesMap {
            get {
                return ResourceManager.GetString("Tab_Settings_UseWormholesMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы успешно авторизовались в EveJima. Мы отслеживаем ваше местоположение в космосе..
        /// </summary>
        internal static string TextAfterAuthorizationInfo {
            get {
                return ResourceManager.GetString("TextAfterAuthorizationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для авторизации вы должны нажать кнопку CCP SSO. Все ваши личные данные остаются на сайте CCP.
        /// </summary>
        internal static string TextAuthorizationInfo {
            get {
                return ResourceManager.GetString("TextAuthorizationInfo", resourceCulture);
            }
        }
    }
}
